### ISSUE TITLE
Attachments query parameter?

### ISSUE THREAD

**Issue by Elliot128** [IndigoUnited/node-couchdb-iterator#11]
I would like to be able to use this query parameter so that I can get all attachments more easily. Is there a reason that you don't allow all the query params supported by couch?

**Comment by satazor** [comment]
The reasoning is that I force some query parameters when iterating https://github.com/IndigoUnited/node-couchdb-iterator/blob/master/lib/rowsReader.js#L36.

Still, instead of whitelisting I should be blacklisting those parameters. Could you do a PR to change to a blacklist of parameters instead? Ty

**Comment by satazor** [comment]
@Elliot128 any news on this? Going to close but feel free to make a PR.
